apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
data:
  JENKINS_URL: http://localhost
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
type: Opaque
data:
  JENKINS_USER: YWRtaW4= # admin
  JENKINS_PASSWORD: YWRtaW4= # admin
